[tool.black]
line-length = 120
[project]
name = "waves"
version = "1.3"
description = ""
authors = [
    {name = "Jeroen Ritmeester",email = "jeroen.c.ritmeester@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyserial (>=3.5,<4.0)",
    "pyqt5 (>=5.15.11,<6.0.0)",
    "pycaw (>=20240210,<20240211)",
    "comtypes (>=1.4.10,<2.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
