class MicrocontrollerProtocol:
    def connect(self, port: str, baudrate: int) -> None: ...
    def read_values(self) -> list[float]: ...
    def close(self) -> None: ...

    @property
    def is_connected(self) -> bool: ...
