from typing import Protocol
from pathlib import Path


class ConfigManagerProtocol(Protocol):
    """Define the interface we expect from ConfigManager"""

    def get_setting(self, text: str) -> str: ...
    def load_config(self) -> None: ...
    def get_serial_port(self) -> str: ...
    def get_default_config_path(self) -> Path: ...
