name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Install dev tools
        run: pip install python-semantic-release

      - name: (debug) Preview version bump
        shell: bash
        run: |
          echo ">>> semantic-release version --no-push --skip-build"
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} semantic-release version --no-push --skip-build
          
      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Semantic Release
        shell: bash
        run: |
          echo ">>> Running semantic-release with GitHub token"
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} semantic-release -vvv publish
